- src/main/java/io/xlate/edi/internal/schema/SchemaReaderBase.java
- src/test/java/io/xlate/edi/internal/schema/StaEDISchemaFactoryTest.java
- src/test/java/io/xlate/edi/internal/schema/StaEDISchemaTest.java
- src/test/resources/EDIFACT/CONTRL-v4r02.xml
- src/test/resources/EDIFACT/fragment-uci-duplicate-element-names.xml
- src/test/resources/EDIFACT/fragment-uci-invalid-min-occurs.xml
- src/test/resources/EDIFACT/fragment-uci-invalid-syntax-type.xml
Fixes #19 
Fix handling of multiple syntax elements
- Add tests for several exception cases
> Fix handling of multiple syntax elements

- src/main/java/io/xlate/edi/internal/schema/SchemaReaderBase.java
- src/main/java/io/xlate/edi/internal/schema/StaEDISchema.java
- src/main/java/io/xlate/edi/internal/stream/validation/Validator.java
- src/main/resources/schema/EDISchema-v3.xsd
- src/test/java/io/xlate/edi/internal/schema/StaEDISchemaFactoryTest.java
- src/test/java/io/xlate/edi/internal/stream/ErrorEventsTest.java
- src/test/resources/x12/EDISchema997_support_any_elements.xml
> Support for lax validation of simple elements and composite elements

- src/main/java/io/xlate/edi/internal/stream/StaEDIOutputFactory.java
- src/main/java/io/xlate/edi/internal/stream/StaEDIStreamWriter.java
- src/main/java/io/xlate/edi/stream/EDIOutputFactory.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamWriterTest.java
> Add option to suppress trailing empty elements

- src/main/java/io/xlate/edi/internal/stream/StaEDIStreamWriter.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamWriterTest.java
> Do not add new line (pretty print) when segment terminator is new line

- src/main/java/io/xlate/edi/internal/stream/tokenization/EDIFACTDialect.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamReaderTest.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamWriterTest.java
- src/test/java/io/xlate/edi/internal/stream/tokenization/EDIFACTDialectTest.java
> Delay EDIFACT version parse until end of composite element UNB01

- src/main/java/io/xlate/edi/internal/stream/tokenization/Lexer.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIXMLStreamReaderTest.java
> Throw EDIStreamException immediately from Lexer#parser in INVALID state

- src/main/resources/X12/common.xml
- src/test/java/io/xlate/edi/internal/stream/EventSequenceTest.java
> Correct order of GE segment's elements in X12 control schema

- src/main/java/io/xlate/edi/internal/stream/tokenization/ProxyEventHandler.java
- src/main/java/io/xlate/edi/internal/stream/validation/Validator.java
- src/test/java/io/xlate/edi/internal/schema/implementation/ElementImplTest.java
- src/test/java/io/xlate/edi/internal/schema/implementation/SegmentImplTest.java
- src/test/resources/x12/005010/837.xml
- src/test/resources/x12/005010X222/837_loop1000_only.xml
- Update START_SEGMENT event with impl segment when selected
> Return impl schema types from validator when available

- src/main/java/io/xlate/edi/internal/stream/StaEDIXMLStreamWriter.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIXMLStreamWriterTest.java
> Allow element gaps - require proper element and composite naming

- .github/workflows/build.yml
- pom.xml
- src/main/java/io/xlate/edi/internal/stream/StaEDIStreamWriter.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamWriterTest.java
- src/test/java/io/xlate/edi/internal/stream/validation/DateValidatorTest.java
- src/test/java/io/xlate/edi/test/StaEDITestUtil.java
>  Validate composite position when writing first component

- .github/workflows/build.yml
- src/main/java/io/xlate/edi/internal/stream/validation/SyntaxValidator.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamReaderSyntaxTest.java
- src/test/java/io/xlate/edi/internal/stream/validation/ListSyntaxValidatorTest.java
- src/test/java/io/xlate/edi/internal/stream/validation/SyntaxValidatorTestBase.java
> Use composite index as element position for syntax error event 

- src/main/java/io/xlate/edi/internal/stream/tokenization/Dialect.java
- src/main/java/io/xlate/edi/internal/stream/tokenization/EDIFACTDialect.java
- src/main/java/io/xlate/edi/internal/stream/validation/DecimalValidator.java
- src/test/java/io/xlate/edi/internal/stream/tokenization/EDIFACTDialectTest.java
> Ignore decimal value from service advice segment, version 4 and after

- src/main/java/io/xlate/edi/internal/stream/StaEDIStreamWriter.java
- src/main/java/io/xlate/edi/internal/stream/tokenization/EDIFACTDialect.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIStreamWriterTest.java
> Fix handling of UNB terminated prematurely

- .github/workflows/build.yml
- .github/workflows/quality.yml
Signed-off-by: Michael Edgar <michael@xlate.io>
> Workflow enhancements 4

- src/main/java/io/xlate/edi/internal/schema/ElementType.java
- src/main/java/io/xlate/edi/internal/schema/SchemaReaderBase.java
- src/main/java/io/xlate/edi/internal/schema/SchemaReaderV3.java
- src/main/java/io/xlate/edi/internal/schema/implementation/ElementImpl.java
- src/main/java/io/xlate/edi/schema/EDISimpleType.java
- src/main/java/io/xlate/edi/schema/implementation/ElementImplementation.java
- src/test/java/io/xlate/edi/internal/schema/ElementTypeTest.java
- src/test/java/io/xlate/edi/internal/schema/implementation/ElementImplTest.java
- src/test/java/io/xlate/edi/internal/schema/implementation/SegmentImplTest.java
- src/test/java/io/xlate/edi/internal/stream/validation/AlphaNumericValidatorTest.java
- src/test/java/io/xlate/edi/internal/stream/validation/ValueSetTester.java
- src/test/resources/x12/005010X222/837_loop1000_only.xml
> Store and provide access to the titles of enumerated element values

- .github/workflows/codeql-analysis.yml
> Bump `CodeQL` workflow action versions to latest majors

- .github/workflows/build.yml
- .github/workflows/sonar-analysis.yml
Part of fix for https://github.com/xlate/staedi/issues/304
> Bump action versions for build and Sonar workflows

- src/main/java/io/xlate/edi/internal/stream/StaEDIStreamWriter.java
- src/main/java/io/xlate/edi/internal/stream/StaEDIXMLStreamReader.java
- src/main/java/io/xlate/edi/internal/stream/tokenization/ProxyEventHandler.java
- src/main/java/io/xlate/edi/internal/stream/tokenization/StreamEvent.java
- src/main/java/io/xlate/edi/internal/stream/validation/Validator.java
- src/main/java/io/xlate/edi/stream/EDIInputFactory.java
- src/test/java/io/xlate/edi/internal/stream/SegmentValidationTest.java
- src/test/java/io/xlate/edi/internal/stream/StaEDIXMLStreamReaderTest.java
> Fix selection of implementation loops/segments in EDI writer

- src/main/java/io/xlate/edi/internal/stream/validation/ControlUsageNode.java
- src/test/java/io/xlate/edi/internal/stream/ErrorEventsTest.java
> fix: strip leading zeros before comparing trailer control counts

- src/main/java/io/xlate/edi/internal/stream/tokenization/Lexer.java
Make the `Lexer` slightly easier to read and debug.
> Refactor handler lambdas in Lexer to be methods/references
